### ISSUE TITLE
Request a feature for setting different chatgpt model

### ISSUE THREAD

**Issue by ChunwuZhu** [yanxiaodi/vs-code-revision#10]
Hi,

I recently encountered an error saying the model is deprecated. Is it possible to set an option for this extension to customize the chatgpt model?

![Snipaste_2024-01-21_19-07-43](https://github.com/yanxiaodi/vs-code-revision/assets/16146653/7a98f69f-8c58-45bd-a748-d39f4847be30)

Thanks!

**Comment by yanxiaodi** [comment]
Hi @ChunwuZhu , thanks for your feedback. I think it's a good idea to provide this feature. I'll update it soon.

**Comment by yanxiaodi** [comment]
Hi @ChunwuZhu the new version has been released: https://marketplace.visualstudio.com/items?itemName=XiaodiYan.revision
It supports `gpt-3.5-turbo-instruct` by default and you can configure it as well. Let me know if you have any issues. Thanks.

**Comment by ChunwuZhu** [comment]
Thank you very much, that is very helpful!
