### ISSUE TITLE
Can you provide a setting option to revise the prompt?

### ISSUE THREAD

**Issue by ChunwuZhu** [yanxiaodi/vs-code-revision#6]
Hi, can you provide a setting option to revise the prompt? The current prompt is not flexible when I have some specific revise or translate needs. Thanks!

**Comment by ChunwuZhu** [comment]
For example, for translation, we don't need to preset the source language and target language in the setting. Such presetting limits the language to be translated and lacks flexibility. It's better that we can revise the prompt like "translate the following content to English if it's Chinese or otherwise". Such a prompt is more flexible when we want to translate the content from English to Chinese or from the other direction.

**Comment by yanxiaodi** [comment]
That's a good point. Perhaps we just need a target language setting? I'll think about that.

**Comment by ChunwuZhu** [comment]
Thanks!

**Comment by ChunwuZhu** [comment]
> 

It's better to have the option to customize the prompt to have more flexibility, not just limited to language configuration. Thanks!

**Comment by yanxiaodi** [comment]
I'll think about how to implement this. Thanks for your feedback.

**Comment by yanxiaodi** [comment]
@ChunwuZhu Updated in #9 . You can have a try.

**Comment by ChunwuZhu** [comment]
Thanks!
